import type { Metadata } from "next";
import { Inter, Cairo } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";

const inter = Inter({ subsets: ["latin"] });
const cario = Cairo({
  weight: ["400", "700"],
  style: ["normal"],
  subsets: ["arabic"],
});

export const metadata: Metadata = {
  title: "Cloud Hosting App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cario.className}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
