import type { Metadata } from "next";
import { Inter, Cairo } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });
const cario = Cairo({
  weight: ["400", "700"],
  style: ["normal"],
  subsets: ["arabic"],
});

export const metadata: Metadata = {
  title: "Cloud Hosting App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cario.className}>
        <Header />
        <ToastContainer position="top-center" limit={2} />
        <main className="mt-[120px]">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
